apiVersion: argoproj.io/v1alpha1
kind: Rollout  # CRD kind
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:        # deployment strategy to use
      canaryService: rollouts-demo-canary  # canary service name
      stableService: rollouts-demo-stable  # stable service name
      trafficRouting:
        nginx:
          stableIngress: rollouts-demo-stable  #ingress name
      steps:
      - setWeight: 5  # percentage of traffic to be routed to new version
      - pause: {}  # pausing indefinitely after rolling out the new version 
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:yellow
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
